# /pnpm-workspace.yaml
packages:
  - 'apps/registry/front-end'
  - 'packages/cli'
  - 'packages/prisma'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  vue-demi: true
