//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organization")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "custom(\"citext\")", unique)]
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::organization_member::Entity")]
    OrganizationMember,
    #[sea_orm(has_many = "super::package::Entity")]
    Package,
}

impl Related<super::organization_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationMember.def()
    }
}

impl Related<super::package::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Package.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::organization_member::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::organization_member::Relation::Organization
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
