//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "custom(\"citext\")", unique)]
    pub username: String,
    pub nickname: String,
    pub avatar: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::organization_member::Entity")]
    OrganizationMember,
    #[sea_orm(has_many = "super::token::Entity")]
    Token,
    #[sea_orm(has_many = "super::user_refresh_token::Entity")]
    UserRefreshToken,
}

impl Related<super::organization_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationMember.def()
    }
}

impl Related<super::token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Token.def()
    }
}

impl Related<super::user_refresh_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRefreshToken.def()
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        super::organization_member::Relation::Organization.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::organization_member::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
